### ISSUE TITLE
copper-lamp graphic is Low rez

### ISSUE THREAD

**Issue by Maxoxpower** [goakiller900/Larger-Lamps#15]
copper-lamp graphic is Low rez but electric one is Hr.

need to fix the copper-lamp graphic

**Comment by goakiller900** [comment]
See what you mean, spend 5 hours trying to fix this. But since the original code is out of standard, I could not fix it 
code need a rewrite , but iam not willing,. known issue but cant fix it

(only time i got it fixed the burner lamps was 4 times bigger ingame... but high ress.)
