### ISSUE TITLE
Mining time is being ignored

### ISSUE THREAD

**Issue by goakiller900** [goakiller900/Larger-Lamps#6]
Mining time in the script is ignored, not entirely sure why this is

**Comment by NullHarp** [comment]
il check it out once i have a chance

**Comment by NullHarp** [comment]
just checked it out i think its working correctly the mining time is set to 2.0 so thats two seconds to mine

**Comment by NullHarp** [comment]
tho honestly it should prob be something like 0.2 or smthin

**Comment by goakiller900** [comment]
@NullHarp iam down with pneumonia so i dont mind uploading the mod to factoriomods once requested but iam afk for abit apart from that, first need to learn to breath again ^^

**Comment by NullHarp** [comment]
oh geez, feel better soon :)
